print("Application started")

AWS_ACCESS_KEY = "AKIA1234567890ABCDE"
STRIPE_SECRET = "sk_live_1234567890ABCDEFGHIJKLMNOPQRSTUVW"

print("AWS_ACCESS_KEY =", AWS_ACCESS_KEY)
print("STRIPE_SECRET =", STRIPE_SECRET)

print("Application finished")
