
print("Application started")

AWS_ACCESS_KEY = "AKIAABCDEFGHIJKLMNOP"
STRIPE_SECRET = "sk_live_ABCDEFGHIJKLMNOPQRSTUVWXYZ1234"

print("AWS_ACCESS_KEY =", AWS_ACCESS_KEY)
print("STRIPE_SECRET =", STRIPE_SECRET)

print("Application finished")

